### ISSUE TITLE
Thread.sleep and thermocouple code?

### ISSUE THREAD

**Issue by RNubla** [Quadforge/guPiBlaster2#3]
Why Thread.sleep cannot be used and should we still use the old thermocouple code?

**Comment by codyfinn** [comment]
Thread.sleep() pauses the execution of the thread [https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#sleep(long)](url). Since our current project only has one thread all execution will stop. Also it is the ServoBlaser daemon's job to create pulses not guPiBlaster's. Make sure you understand the thermocouple code. That was not written by anyone in the project I recommend looking for ways to improve it.
